user_app/urls.py
from django.conf.urls import url
from user_app import views

#Template URLs
app_name = 'user_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

user_authentication/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from user_app import views

urlpatterns = [
    url(r'index/', views.index, name='index'),
    path(r'admin/', admin.site.urls),
    url(r'^user_app/', include('user_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special')
]

user_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (be sure not to inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User
        return self.user.username

user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from user_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

user_app/views.py
from django.shortcuts import render
from user_app.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def index(request):
    return render(request, 'user_app/index.html')


# require user login with decorator for special login notification function and logout function
@login_required
def special(request):
    return HttpResponse("You're logged in!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    # check if user is registered
    registered = False

    if request.method == 'POST':
        # grab information from user form
        user_form = UserForm(data=request.POST)
        # grab information from profile info form
        profile_form = UserProfileInfoForm(data=request.POST)

        # check if both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # grab user form and save it to database
            user = user_form.save()
            # hash password with set method
            user.set_password(user.password)
            # save hashed password
            user.save()

            profile = profile_form.save(commit=False)
            # define one to one relationship
            profile.user = user

            # check for proile picture
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            # save model
            profile.save()
            # set user as registered
            registered = True

        else:
            # if either form is invalid print error
            print(user_form.errors, profile_form.errors)
    # if user never posts any information to forms, set user and profile forms
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    # return forms
    return render(request, 'user_app/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered' : registered})


def user_login(request):

        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            # automatic user authentication
            user = authenticate(username=username, password=password)

            if user:
                # if account is active redirect user to homepage index
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('index'))
                # if account is inactive respond with account not active
                else:
                    return HttpResponse("ACCOUNT NOT ACTIVE")
            else:
                print("Someone tried to login and failed!")
                print("Username: {} and password {}".format(username, password))
                return HttpResponse("INVALID LOGIN DETAILS")
        # if user submits nothing return login page
        else:
            return render(request, 'user_app/login.html', {})

templates/user_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="navbar-item">
                    <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
                </li>
                <li class="navbar-item">
                    <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="navbar-item">
                    <a class="navbar-link" href="{% url 'user_app:register'%}">Register</a>
                </li>

                {% if user.is_authenticated %}
                <li class="navbar-item"><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="navbar-item"><a class="navbar-link" href="{% url 'user_app:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div>
        {% block body_block %}

        {% endblock %}
    </div>
</body>

</html>

templates/user_app/index.html
{% extends 'user_app/base.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Django Level Five</h1>
    </div>
</div>
{% endblock %}

templates/user_app/login.html
{% extends 'user_app/base.html' %}
{% block body_block %}

<div>
    <h1>Please Login</h1>
    <form action="{% url 'user_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>
</div>
{% endblock %}

templates/user_app/registration.html
{% extends 'user_app/base.html' %}

{% load staticfiles %}

{% block body_block %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
        <h1>Thanks for registering!</h1>
        {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register" />
        </form>

        {% endif %}
    </div>
</div>
{% endblock %}